apiVersion: v1
kind: Namespace
metadata:
  name: starbucks-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-app-deployment
  namespace: starbucks-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: starbucks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: starbucks-app
    spec:
      containers:
        - name: starbucks-app
          image: prodaksclusterregistry.azurecr.io/starbucks:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
