apiVersion: v1
kind: Service
metadata:
  name: starbucks-app-service
  namespace: starbucks-ns
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: starbucks-app
  ports:
    - port: 80
      targetPort: 80